apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: myweb
        image: kumarolipi/jenkins-docker:latest
        ports:
        - containerPort: 80
