apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany  # Adjust access mode based on your PV
  storageClassName: manual  # Set to the storage class name used by your PV, or leave it empty for manual allocation
  resources:
    requests:
      storage: 500Mi
