apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-1
spec:
  rules:
  - host: www.kumarolipi.in
    http:
      paths:
      - backend:
          serviceName: nginx-deploy-main
          servicePort: 80

