apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: nfs-subdir-external-provisioner
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-01T03:32:50Z"
  generation: 1
  labels:
    app: nfs-subdir-external-provisioner
    app.kubernetes.io/managed-by: Helm
    chart: nfs-subdir-external-provisioner-4.0.18
    heritage: Helm
    release: nfs-subdir-external-provisioner
  name: nfs-subdir-external-provisioner
  namespace: default
  resourceVersion: "363848"
  uid: c601ee5b-1813-42a9-9f29-bdc462c7ddf8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nfs-subdir-external-provisioner
      release: nfs-subdir-external-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nfs-subdir-external-provisioner
        release: nfs-subdir-external-provisioner
    spec:
      containers:
      - env:
        - name: PROVISIONER_NAME
          value: cluster.local/nfs-subdir-external-provisioner
        - name: NFS_SERVER
          value: 13.127.142.182
        - name: NFS_PATH
          value: /srv/nfs/kubedata
        image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
        imagePullPolicy: IfNotPresent
        name: nfs-subdir-external-provisioner
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /persistentvolumes
          name: nfs-subdir-external-provisioner-root
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nfs-subdir-external-provisioner
      serviceAccountName: nfs-subdir-external-provisioner
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs-subdir-external-provisioner-root
        nfs:
          path: /srv/nfs/kubedata
          server: 13.127.142.182
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-12-01T03:33:01Z"
    lastUpdateTime: "2023-12-01T03:33:01Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-12-01T03:32:51Z"
    lastUpdateTime: "2023-12-01T03:33:01Z"
    message: ReplicaSet "nfs-subdir-external-provisioner-8874cbd89" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

