apiVersion: v1
kind: Pod
metadata:
  name: busybox2
spec:
  volumes:
  - name: myvol
    persistentVolumeClaim:
      claimName: pvc-nfs2
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    volumeMounts:
    - name: myvol
      mountPath: /mydata

